# RCODE
upstr1=read.table(file="FCm_upstream_100_1.composition",header=T,sep="\t",comment.char='')
upstr2=read.table(file="FCm_upstream_200_100.composition",header=T,sep="\t",comment.char='')
upstr3=read.table(file="FCm_upstream_300_200.composition",header=T,sep="\t",comment.char='')
upstr4=read.table(file="FCm_upstream_400_300.composition",header=T,sep="\t",comment.char='')
inter=read.table(file="FCm_intergenic.composition",header=T,sep="\t",comment.char='')
intro=read.table(file="FCm_intronic.composition",header=T,sep="\t",comment.char='') 
exoni=read.table(file="FCm_exonic.composition",header=T,sep="\t",comment.char='')

# par(mfrow=c(2,2))
# boxplot(upstr[,2:5],main='upstream')
# boxplot(inter[,2:5],main='intergenic')
# boxplot(intro[,2:5],main='intronic')
# boxplot(exoni[,2:5],main='exonic')

# par(mfrow=c(2,2))
# boxplot(upstr[,2:5],main='upstream',ylim=c(0,0.6))
# boxplot(inter[,2:5],main='intergenic',ylim=c(0,0.6))
# boxplot(intro[,2:5],main='intronic',ylim=c(0,0.6))
# boxplot(exoni[,2:5],main='exonic',ylim=c(0,0.6))

pdf(file='FCm_regional_composition.pdf',paper='a4r',width=8.3,height=11.7,pointsize=8,title='FCm bases composition')
par(mfrow=c(1,4))
boxplot(upstr1[,2:5],main='FCm upstream -100 / 0',ylim=c(0,0.58),notch=F,outline=F,col=8)
boxplot(inter[,2:5],main='FCm intergenic',ylim=c(0,0.58),notch=F,outline=F,col=8)
boxplot(intro[,2:5],main='FCm intronic',ylim=c(0,0.58),notch=F,outline=F,col=8)
boxplot(exoni[,2:5],main='FCm exonic',ylim=c(0,0.58),notch=F,outline=F,col=8)
dev.off()

pdf(file='FCm_upstream_regional_composition.pdf',paper='a4r',width=8.3,height=11.7,pointsize=8,title='FCm upstream bases composition')
par(mfrow=c(1,4))
boxplot(upstr1[,2:5],main='FCm upstream -100 / 0',ylim=c(0,0.58),notch=F,outline=F,col=8)
boxplot(upstr2[,2:5],main='FCm upstream -200 / -100',ylim=c(0,0.58),notch=F,outline=F,col=8)
boxplot(upstr3[,2:5],main='FCm upstream -300 / -200',ylim=c(0,0.58),notch=F,outline=F,col=8)
boxplot(upstr4[,2:5],main='FCm upstream -400 / -300',ylim=c(0,0.58),notch=F,outline=F,col=8)
dev.off()
